version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mystore
      - POSTGRES_USER=fabian
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgres/data

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=mystore
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  mysql_data2:
